# Generated by Django 6.0.6 on 2026-06-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='hall',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='recording_mode',
            field=models.CharField(choices=[('manual', 'Manual analysis'), ('auto', 'Auto recording')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'INSTRUCTOR', 'DEAN']}, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['scheduled_date'], name='apis_exam_schedul_d432c9_idx'),
        ),
    ]
