# Generated by Django 5.2.13 on 2026-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='behavior_type',
            field=models.CharField(choices=[('PHONE_DETECTED', 'Phone Detected'), ('LOOKING_AWAY', 'Looking Away'), ('LAPTOPS', 'Laptop Detected')], max_length=50),
        ),
    ]
