# Generated by Django 5.2.12 on 2026-05-05 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('ai_model_version', models.CharField(blank=True, max_length=100)),
                ('frame_sample_rate', models.PositiveIntegerField(default=1, help_text='Analyze every Nth frame.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_cheating_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('alerts_by_type', models.JSONField(blank=True, default=dict)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot_url',
            field=models.URLField(blank=True, help_text='URL to the frame snapshot showing visual evidence.', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-delete video after this date.', null=True),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['expires_at'], name='apis_video_expires_cf6bb6_idx'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='apis.examsession'),
        ),
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='apis.examsession'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'created_at'], name='apis_analys_status_080e47_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['overall_cheating_probability'], name='apis_report_overall_b304c6_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_at'], name='apis_report_generat_debc32_idx'),
        ),
    ]
