# Generated by Django 6.0.6 on 2026-06-13 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=120)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('academic_year', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='apis_studen_owner_i_0678d3_idx'), models.Index(fields=['student_id'], name='apis_studen_student_c18aff_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'student_id'), name='unique_student_id_per_owner')],
            },
        ),
    ]
