# Generated by Django 5.2.13 on 2026-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_alert_behavior_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIDEO_UPLOADED', 'Video Uploaded'), ('VIDEO_DELETED', 'Video Deleted'), ('ANALYSIS_STARTED', 'AI Analysis Started'), ('ANALYSIS_COMPLETED', 'AI Analysis Completed'), ('ANALYSIS_FAILED', 'AI Analysis Failed'), ('SETTINGS_CHANGED', 'Settings Changed'), ('ALERT_REVIEWED', 'Alert Reviewed'), ('REPORT_GENERATED', 'Report Generated'), ('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('EXAM_DELETED', 'Exam Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('EXAM_ASSIGNED', 'Exam Assigned'), ('EXAM_UPDATED', 'Exam Updated'), ('EXAM_CANCELLED', 'Exam Cancelled'), ('ANALYSIS_FAILED', 'Analysis Failed'), ('WORKSPACE_INVITE', 'Workspace Invite'), ('INVITE_ACCEPTED', 'Invite Accepted'), ('INVITE_DECLINED', 'Invite Declined')], max_length=32),
        ),
    ]
