# Generated by Django 5.2.13 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_auditlog_action_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='frame_sample_rate',
            field=models.PositiveIntegerField(default=15, help_text='Analyze every Nth frame (1 = every frame).'),
        ),
    ]
