# Generated by Django 5.2.13 on 2026-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('INSTRUCTOR', 'Instructor')], default='INSTRUCTOR', max_length=20),
        ),
    ]
