# Generated by Django 5.2.13 on 2026-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DEAN', 'Dean'), ('INSTRUCTOR', 'Instructor')], default='INSTRUCTOR', max_length=20),
        ),
    ]
