# Generated by Django 6.0.6 on 2026-06-14 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('is_auto', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_sessions', to='apis.exam')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['instructor', 'scheduled_start'], name='apis_autoex_instruc_b6e11c_idx')],
            },
        ),
    ]
