# Generated by Django 6.0.6 on 2026-06-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_exam_color_exam_course_exam_end_time_exam_hall_and_more'),
        ('apis', '0004_alter_analysisjob_frame_sample_rate'),
    ]

    operations = [
    ]
