# Generated by Django 5.2.13 on 2026-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='behavior_type',
            field=models.CharField(choices=[('PHONE_DETECTED', 'Phone Detected'), ('MULTIPLE_FACES', 'Multiple Faces'), ('LOOKING_AWAY', 'Looking Away'), ('OTHER_PERSON', 'Other Person Detected'), ('OBJECT_DETECTED', 'Unauthorized Object Detected'), ('LAPTOPS', 'Laptop Detected')], max_length=50),
        ),
    ]
