# Generated by Django 6.0.6 on 2026-06-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_autoexamsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='The user who actually uploaded or recorded this video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('session', 'file_hash'), name='unique_video_hash_per_session'),
        ),
    ]
