# Generated by Django 6.0.6 on 2026-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_video_uploaded_by_alter_video_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_dismissed', 'created_at'], name='apis_notifi_recipie_446b6b_idx'),
        ),
    ]
