# Generated by Django 6.0.6 on 2026-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_notification_is_dismissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='clip_url',
            field=models.CharField(blank=True, help_text='URL to the 3-second video clip centred on this alert.', max_length=500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snapshot_url',
            field=models.URLField(blank=True, help_text='URL to the cropped face image of the flagged person at this alert.', max_length=500),
        ),
    ]
