# Generated by Django 5.2.13 on 2026-04-10 21:55

import proctoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='alert_threshold',
            field=models.FloatField(default=0.65, help_text='Cheating probability above this triggers alerts (0–1).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Raw video files older than this are deleted.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=proctoring.models.video_upload_to),
        ),
    ]
