
from django.urls import path

from .views import (
    AnalyzeVideoView,
    AutoSessionDetailView,
    AutoSessionListCreateView,
    DashboardActivityView,
    DashboardStatsView,
    DeleteUserView,
    ExamListView,
    ExamResolveView,
    GlobalThresholdsView,
    HallManagementView,
    InstructorOversightView,
    InviteRespondView,
    MarkNotificationsReadView,
    MyPreferencesView,
    MyThresholdsView,
    NotificationListView,
    SessionVideoStatusView,
    StudentDetailView,
    StudentListCreateView,
    SystemLogsView,
    SystemMetricsView,
    ThresholdsView,
    UnreadNotificationsView,
    UserActivityView,
    UserLookupView,
    UsersListView,
    VideoDetailView,
    VideoHistoryView,
    VideoListView,
    VideoUploadView,
    WorkspaceInviteView,
)

urlpatterns = [
    path('', UsersListView.as_view(), name='users_list'),
    path('me/preferences/', MyPreferencesView.as_view(), name='my_preferences'),
    path('users/lookup/', UserLookupView.as_view(), name='users_lookup'),
    path('students/', StudentListCreateView.as_view(), name='students_list'),
    path('students/<uuid:pk>/', StudentDetailView.as_view(), name='students_detail'),
    path('videos/', VideoListView.as_view(), name='videos_list'),
    path('videos/upload/', VideoUploadView.as_view(), name='videos_upload'),
    path('videos/<uuid:pk>/', VideoDetailView.as_view(), name='videos_detail'),
    path('videos/<uuid:pk>/analyze/', AnalyzeVideoView.as_view(), name='videos_analyze'),
    path('history/', VideoHistoryView.as_view(), name='videos_history'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard_stats'),
    path('dashboard/activity/', DashboardActivityView.as_view(), name='dashboard_activity'),
    path('thresholds/', ThresholdsView.as_view(), name='thresholds'),
    path('thresholds/me/', MyThresholdsView.as_view(), name='my_thresholds'),
    path('thresholds/global/', GlobalThresholdsView.as_view(), name='global_thresholds'),
    path('system/logs/', SystemLogsView.as_view(), name='system_logs'),
    path('system/metrics/', SystemMetricsView.as_view(), name='system_metrics'),
    path('dean/instructors/', InstructorOversightView.as_view(), name='dean_instructor_oversight'),
    path('dean/halls/', HallManagementView.as_view(), name='dean_hall_management'),
    path('notifications/', NotificationListView.as_view(), name='notifications_list'),
    path('notifications/unread/', UnreadNotificationsView.as_view(), name='notifications_unread'),
    path('notifications/mark-read/', MarkNotificationsReadView.as_view(), name='notifications_mark_read'),
    path('workspace/invite/', WorkspaceInviteView.as_view(), name='workspace_invite'),
    path('invite/<uuid:token>/accept/', InviteRespondView.as_view(accepted=True), name='invite_accept'),
    path('invite/<uuid:token>/decline/', InviteRespondView.as_view(accepted=False), name='invite_decline'),
    path('auto-sessions/', AutoSessionListCreateView.as_view(), name='auto_sessions'),
    path('auto-sessions/<uuid:pk>/', AutoSessionDetailView.as_view(), name='auto_session_detail'),
    path('exams/', ExamListView.as_view(), name='exams_list'),
    path('exams/resolve/', ExamResolveView.as_view(), name='exams_resolve'),
    path('sessions/<uuid:exam_id>/video-status/', SessionVideoStatusView.as_view(), name='session_video_status'),
    path('<uuid:pk>/activity/', UserActivityView.as_view(), name='user_activity'),
    path('<uuid:pk>/', DeleteUserView.as_view(), name='delete_user'),
]
