
from django.urls import path

from .views import (
    AlertReviewView,
    AllWorkspaceMembersView,
    AnalysisSessionsView,
    AnalyzeVideoView,
    AutoSessionDetailView,
    AutoSessionListCreateView,
    DashboardActivityView,
    DashboardStatsView,
    DeleteUserView,
    DismissAllNotificationsView,
    DismissNotificationView,
    ExamDetailView,
    ExamListView,
    ExamResolveView,
    GlobalThresholdsView,
    HallManagementView,
    InstructorOversightView,
    InviteRespondView,
    MarkNotificationsReadView,
    MyPreferencesView,
    MyThresholdsView,
    MyWorkspacesView,
    NotificationListView,
    SessionReportView,
    SessionVideoStatusView,
    StudentDetailView,
    StudentListCreateView,
    SystemLogsView,
    SystemMetricsView,
    ThresholdsView,
    UnreadNotificationsView,
    UserActivityView,
    UserLookupView,
    UsersListView,
    VideoDetailView,
    VideoHistoryView,
    VideoListView,
    VideoUploadView,
    WorkspaceDetailView,
    WorkspaceInviteView,
    WorkspaceListCreateView,
    WorkspaceMemberDetailView,
    WorkspaceMembersView,
)

urlpatterns = [
    path('', UsersListView.as_view(), name='users_list'),
    path('me/preferences/', MyPreferencesView.as_view(), name='my_preferences'),
    path('me/workspaces/', MyWorkspacesView.as_view(), name='my_workspaces'),
    path('users/lookup/', UserLookupView.as_view(), name='users_lookup'),
    path('students/', StudentListCreateView.as_view(), name='students_list'),
    path('students/<uuid:pk>/', StudentDetailView.as_view(), name='students_detail'),
    path('videos/', VideoListView.as_view(), name='videos_list'),
    path('videos/upload/', VideoUploadView.as_view(), name='videos_upload'),
    path('videos/<uuid:pk>/', VideoDetailView.as_view(), name='videos_detail'),
    path('videos/<uuid:pk>/analyze/', AnalyzeVideoView.as_view(), name='videos_analyze'),
    path('history/', VideoHistoryView.as_view(), name='videos_history'),
    path('analysis/sessions/', AnalysisSessionsView.as_view(), name='analysis_sessions'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard_stats'),
    path('dashboard/activity/', DashboardActivityView.as_view(), name='dashboard_activity'),
    path('thresholds/', ThresholdsView.as_view(), name='thresholds'),
    path('thresholds/me/', MyThresholdsView.as_view(), name='my_thresholds'),
    path('thresholds/global/', GlobalThresholdsView.as_view(), name='global_thresholds'),
    path('system/logs/', SystemLogsView.as_view(), name='system_logs'),
    path('system/metrics/', SystemMetricsView.as_view(), name='system_metrics'),
    path('dean/instructors/', InstructorOversightView.as_view(), name='dean_instructor_oversight'),
    path('dean/halls/', HallManagementView.as_view(), name='dean_hall_management'),
    path('notifications/', NotificationListView.as_view(), name='notifications_list'),
    path('notifications/unread/', UnreadNotificationsView.as_view(), name='notifications_unread'),
    path('notifications/mark-read/', MarkNotificationsReadView.as_view(), name='notifications_mark_read'),
    path('notifications/dismiss-all/', DismissAllNotificationsView.as_view(), name='notifications_dismiss_all'),
    path('notifications/<uuid:pk>/dismiss/', DismissNotificationView.as_view(), name='notifications_dismiss'),
    path('workspaces/', WorkspaceListCreateView.as_view(), name='workspaces_list'),
    path('workspaces/members/all/', AllWorkspaceMembersView.as_view(), name='workspace_members_all'),
    path('workspaces/<uuid:pk>/', WorkspaceDetailView.as_view(), name='workspace_detail'),
    path('workspaces/<uuid:workspace_id>/members/', WorkspaceMembersView.as_view(), name='workspace_members'),
    path('workspaces/<uuid:workspace_id>/members/<uuid:user_id>/', WorkspaceMemberDetailView.as_view(), name='workspace_member_detail'),
    path('workspace/invite/', WorkspaceInviteView.as_view(), name='workspace_invite'),
    path('invite/<uuid:token>/accept/', InviteRespondView.as_view(accepted=True), name='invite_accept'),
    path('invite/<uuid:token>/decline/', InviteRespondView.as_view(accepted=False), name='invite_decline'),
    path('auto-sessions/', AutoSessionListCreateView.as_view(), name='auto_sessions'),
    path('auto-sessions/<uuid:pk>/', AutoSessionDetailView.as_view(), name='auto_session_detail'),
    path('exams/', ExamListView.as_view(), name='exams_list'),
    path('exams/resolve/', ExamResolveView.as_view(), name='exams_resolve'),
    path('exams/<uuid:pk>/', ExamDetailView.as_view(), name='exam_detail'),
    path('sessions/<uuid:exam_id>/video-status/', SessionVideoStatusView.as_view(), name='session_video_status'),
    path('sessions/<uuid:session_id>/report/', SessionReportView.as_view(), name='session_report'),
    path('alerts/<uuid:alert_id>/dismiss/', AlertReviewView.as_view(action='dismiss'), name='alert_dismiss'),
    path('alerts/<uuid:alert_id>/flag/', AlertReviewView.as_view(action='flag'), name='alert_flag'),
    path('<uuid:pk>/activity/', UserActivityView.as_view(), name='user_activity'),
    path('<uuid:pk>/', DeleteUserView.as_view(), name='delete_user'),
]
