"""
Django settings for nomorecheaters project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a local .env file when python-dotenv is available.
# This is optional: in production, real environment variables are used and the
# import simply no-ops if the package isn't installed.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def env(key, default=None):
    """Return an environment variable, or `default` if unset/empty."""
    value = os.environ.get(key)
    return value if value not in (None, '') else default


def env_bool(key, default=False):
    """Return an environment variable coerced to a bool."""
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(key, default=None):
    """Return a comma-separated environment variable as a list of strings."""
    value = os.environ.get(key)
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment; the insecure literal is only a development fallback.
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    'django-insecure-e!*k^6@gyp))lvmg47d4sgb-ea5u5art#8^_!ak1)#1jjz%oh^',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe for production); set DJANGO_DEBUG=true for local dev.
DEBUG = env_bool('DJANGO_DEBUG', True)

# Comma-separated hosts, e.g. "example.com,api.example.com".
# In DEBUG we default to the usual local hosts so dev works with no config.
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1'] if DEBUG else [],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Required for allauth
    'django.contrib.sites',
    
    
    # Rest frameork and token authentication
    'rest_framework',
    "corsheaders",
    'rest_framework.authtoken',
    
    # Allauth packages 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # dj-rest-auth packages
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # Background job queue (analysis worker)
    'django_rq',

    'apis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # For CORS headers to be used by react or any other domain or api
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # all auth middleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# To be used by react or any other domain or api.
# NOTE: django-cors-headers reads CORS_ALLOWED_ORIGINS (the legacy
# CORS_ORIGIN_WHITELIST name was effectively a no-op). Override via env in prod.
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        "http://localhost:3000",
        "http://localhost:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

# Base URL of the React SPA. Used to build the email-confirmation link so it
# lands on the frontend's /account/verify-email/<key> page instead of the API.
FRONTEND_URL = env('FRONTEND_URL', 'http://localhost:5173')


ROOT_URLCONF = 'nomorecheaters.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# settings for allauth
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Default "from" address for outgoing mail (e.g. workspace invites). In dev the
# console backend just prints the message; override in production via env.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'No More Cheaters <no-reply@nomorecheaters.local>')
SITE_ID = 1

# Settings for allauth email login.
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# allauth requires its backend alongside Django's default ModelBackend.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



WSGI_APPLICATION = 'nomorecheaters.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Defaults to local SQLite (zero-config dev); override via env for production
# (e.g. ENGINE=django.db.backends.postgresql + the DB_* vars below).
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': env('DB_USER', ''),
        'PASSWORD': env('DB_PASSWORD', ''),
        'HOST': env('DB_HOST', ''),
        'PORT': env('DB_PORT', ''),
    }
}

# Background job queue (django-rq + Redis)
# https://github.com/rq/django-rq
#
# Analysis runs through this queue (see apis/tasks.run_analysis). By default
# `RQ_ASYNC` is False, so `queue.enqueue(...)` executes the job synchronously
# in-process — no Redis or worker is required for local dev or the test suite.
# In production, run Redis + `python manage.py rqworker default` and set
# RQ_ASYNC=true so uploads return immediately while videos process in the
# background.
REDIS_URL = env('REDIS_URL', 'redis://127.0.0.1:6379/0')
RQ_ASYNC = env_bool('RQ_ASYNC', False)
RQ_QUEUES = {
    'default': {
        'URL': REDIS_URL,
        'DEFAULT_TIMEOUT': env('RQ_DEFAULT_TIMEOUT', 900),
        'ASYNC': RQ_ASYNC,
    },
}
# Async enqueue happens immediately instead of deferring to
# `transaction.on_commit`. `enqueue_analysis` already commits the AnalysisJob
# row before enqueuing (the view runs in autocommit, no wrapping transaction),
# so the worker can never race ahead of the row it needs to read.
RQ = {'COMMIT_MODE': 'auto'}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# dj-rest-auth: expose the custom `role` field on /api/auth/user/ so the
# frontend can route ADMIN / DEAN / INSTRUCTOR without guessing or relying on
# any client-side fallback.
REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'apis.serializers.CustomUserDetailsSerializer',
    # Persist the DEAN/INSTRUCTOR role chosen at signup (see CustomRegisterSerializer).
    'REGISTER_SERIALIZER': 'apis.serializers.CustomRegisterSerializer',
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'apis.User'



