"""
Django settings for nomorecheaters project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a local .env file when python-dotenv is available.
# This is optional: in production, real environment variables are used and the
# import simply no-ops if the package isn't installed.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def env(key, default=None):
    """Return an environment variable, or `default` if unset/empty."""
    value = os.environ.get(key)
    return value if value not in (None, '') else default


def env_bool(key, default=False):
    """Return an environment variable coerced to a bool."""
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(key, default=None):
    """Return a comma-separated environment variable as a list of strings."""
    value = os.environ.get(key)
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment; the insecure literal is only a development fallback.
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    'django-insecure-e!*k^6@gyp))lvmg47d4sgb-ea5u5art#8^_!ak1)#1jjz%oh^',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe for production); set DJANGO_DEBUG=true for local dev.
DEBUG = env_bool('DJANGO_DEBUG', True)

# Comma-separated hosts, e.g. "example.com,api.example.com".
# In DEBUG we default to the usual local hosts so dev works with no config.
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    [
        # Production backend (EC2, behind Nginx + Certbot)
        'nomorecheater.online',
        'www.nomorecheater.online',
        # Local dev
        'localhost',
        '127.0.0.1',
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Required for allauth
    'django.contrib.sites',
    
    
    # Rest frameork and token authentication
    'rest_framework',
    "corsheaders",
    'rest_framework.authtoken',
    
    # Allauth packages 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # dj-rest-auth packages
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # Background job queue (analysis worker)
    'django_rq',

    'apis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # For CORS headers to be used by react or any other domain or api
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # all auth middleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# To be used by react or any other domain or api.
# NOTE: django-cors-headers reads CORS_ALLOWED_ORIGINS (the legacy
# CORS_ORIGIN_WHITELIST name was effectively a no-op). Override via env in prod.
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        # Production frontend (Vercel)
        "https://nomorecheater.site",
        # Local dev
        "http://localhost:3000",
        "http://localhost:8000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

# Origins Django trusts for unsafe (POST/PUT/DELETE) cross-origin requests.
# Django 4+ requires the scheme, e.g. "https://app.nomorecheater.online".
# Behind the Nginx proxy this must list the public frontend + API origin(s).
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        # Production frontend (Vercel)
        'https://nomorecheater.site',
        # Local dev
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ],
)

# Base URL of the React SPA. Used to build the email-confirmation link so it
# lands on the frontend's /account/verify-email/<key> page instead of the API.
FRONTEND_URL = env('FRONTEND_URL', 'https://nomorecheater.site')


ROOT_URLCONF = 'nomorecheaters.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ── Email (workspace invites, verification, password resets) ──────────────────
# When EMAIL_HOST_PASSWORD is set → Resend SMTP. Otherwise → console (dev).
_EMAIL_PASSWORD=env('E...RD', 're_93kfTXxH_DuggCpxZLdiJ9h5u44KKvxFc')
if _EMAIL_PASSWORD:
    EMAIL_BACKEND = env('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = env('EMAIL_HOST', 'smtp.resend.com')
    EMAIL_PORT = int(env('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', 'resend')
    EMAIL_HOST_PASSWORD = _EMAIL_PASSWORD
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'noreply@nomorecheater.online')

SITE_ID = 1

# ── Allauth — email behaviour ────────────────────────────────────────────
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = env('ACCOUNT_EMAIL_VERIFICATION', 'optional')
ACCOUNT_EMAIL_SUBJECT_PREFIX = env('ACCOUNT_EMAIL_SUBJECT_PREFIX', '[No More Cheaters] ')
# How long verification / password-reset links remain valid (days).
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# Prevent enumeration: always say "email sent" even if the account doesn't exist.
ACCOUNT_PREVENT_ENUMERATION = True
# Allow login immediately after signup (unless verification is mandatory).
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# allauth requires its backend alongside Django's default ModelBackend.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



WSGI_APPLICATION = 'nomorecheaters.wsgi.application'

# Behind the Caddy reverse proxy (which terminates HTTPS and forwards plain HTTP
# to the dev server), trust its X-Forwarded-Proto header. Without this, Django
# thinks every request is HTTP and builds http:// media/static URLs, which the
# HTTPS frontend would then block as mixed content. Set unconditionally because
# we run with DEBUG=True (the `if not DEBUG` hardening block below is skipped).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Hardcoded MySQL running locally ON the EC2 instance itself (no RDS).
# Everything is hardcoded on purpose — no environment variables.
# Create the database on the EC2 host with:
#   CREATE DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
#   CREATE USER 'mydb'@'localhost' IDENTIFIED BY 'mydb';
#   GRANT ALL PRIVILEGES ON mydb.* TO 'mydb'@'localhost';
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER': 'mydb',
        'PASSWORD': 'mydb',
        'HOST': 'localhost',
        'PORT': '3306',
        # Keep a connection open for 60s instead of reconnecting per request —
        # meaningful under Gunicorn's persistent workers.
        'CONN_MAX_AGE': 60,
        # utf8mb4 = full Unicode; STRICT mode errors loudly on bad data instead
        # of silently truncating it.
        'OPTIONS': {
            'charset': 'utf8mb4',
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}

# Background job queue (django-rq + Redis)
# https://github.com/rq/django-rq
#
# Analysis runs through this queue (see apis/tasks.run_analysis). By default
# `RQ_ASYNC` is False, so `queue.enqueue(...)` executes the job synchronously
# in-process — no Redis or worker is required for local dev or the test suite.
# In production, run Redis + `python manage.py rqworker default` and set
# RQ_ASYNC=true so uploads return immediately while videos process in the
# background.
REDIS_URL = env('REDIS_URL', 'redis://127.0.0.1:6379/0')
RQ_ASYNC = env_bool('RQ_ASYNC', False)
RQ_QUEUES = {
    'default': {
        'URL': REDIS_URL,
        'DEFAULT_TIMEOUT': env('RQ_DEFAULT_TIMEOUT', 900),
        'ASYNC': RQ_ASYNC,
    },
}
# Async enqueue happens immediately instead of deferring to
# `transaction.on_commit`. `enqueue_analysis` already commits the AnalysisJob
# row before enqueuing (the view runs in autocommit, no wrapping transaction),
# so the worker can never race ahead of the row it needs to read.
RQ = {'COMMIT_MODE': 'auto'}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# dj-rest-auth: expose the custom `role` field on /api/auth/user/ so the
# frontend can route ADMIN / DEAN / INSTRUCTOR without guessing or relying on
# any client-side fallback.
REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'apis.serializers.CustomUserDetailsSerializer',
    # Persist the DEAN/INSTRUCTOR role chosen at signup (see CustomRegisterSerializer).
    'REGISTER_SERIALIZER': 'apis.serializers.CustomRegisterSerializer',
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Leading slashes are required so FileField.url / build_absolute_uri emit
# root-relative paths ('/media/...') instead of paths resolved against the
# current request (e.g. '/api/videos/media/...'), and so they line up with the
# reverse-proxy `location /media/` and `location /static/` blocks in production
# (see deploy/nginx.conf — C3).
STATIC_URL = '/static/'
# Absolute filesystem dir that `collectstatic` writes to and Nginx serves from.
# Unused in DEBUG (Django serves app/admin static itself) but required in prod.
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Hard cap on the size of an uploaded video, enforced in VideoUploadSerializer
# (N2). Mirrors `client_max_body_size 1024m` in deploy/nginx.conf so the proxy
# and the application reject the same threshold — Nginx rejects oversized
# bodies before they reach Gunicorn, this catches anything that bypasses it
# (e.g. the dev server, or a misconfigured proxy).
MAX_UPLOAD_SIZE_BYTES = 1024 * 1024 * 1024  # 1 GiB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'apis.User'


# ── Production security hardening ─────────────────────────────────────────────
# Active only when DEBUG is off (i.e. on EC2). Local dev over plain HTTP is
# unaffected. These assume the app sits behind the Nginx reverse proxy in
# deploy/nginx.conf, which terminates TLS and forwards X-Forwarded-Proto.
if not DEBUG:
    # Trust the proxy's X-Forwarded-Proto so Django knows the original request
    # was HTTPS (Gunicorn itself receives plain HTTP from Nginx).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Redirect any HTTP request to HTTPS. Disable via SECURE_SSL_REDIRECT=false
    # if you terminate TLS elsewhere or are still on a bare-IP/HTTP setup.
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)

    # Only send session / CSRF cookies over HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS: tell browsers to stick to HTTPS. Starts at 0 (opt-in) so a
    # misconfigured cert can't lock users out; raise once HTTPS is confirmed
    # stable (e.g. 31536000 = 1 year) and enable the subdomain/preload flags.
    SECURE_HSTS_SECONDS = int(env('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)

    # Defence-in-depth headers.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'



